#!/usr/bin/env python3
"""build-how-it-works.py — regenerate the "How JanVayu works" diagram.

The diagram is the first thing a visitor reads that explains where the numbers
come from, and it had gone stale in a way nobody would notice: every figure on
it was right, and a CI check (`check-site-figures.py`) was holding them right,
so nothing looked wrong. What had drifted was the *inventory*. It listed five
live feeds and four satellite sources and named none of the two largest bodies
of work on the site — eleven years of CPCB's own daily bulletin, and the
measured station record the modelled layers are checked against. On the output
side it offered five things and the site now offers seven.

A check cannot catch that, because there is no number to compare. So the
diagram stops being hand-placed. This file holds the content as a list of
blocks, lays both orientations out arithmetically, and writes them into the
three places the drawing appears:

    index.html            desktop (wide) and phone (tall)
    walkthrough/deck.html the slide deck's copy

Every figure in it is read from the repo at build time — the live city count
from `CITIES` in app.js, the boundary counts from `data/tiles/_levels.json`,
the bulletin panel from `data/aqi-bulletins.json`, the de-weathered panel from
`data/deweathered-national.json`. Nothing here is typed by hand, so the numbers
cannot drift from the data even if nobody re-reads the drawing for a year.

    python3 scripts/build-how-it-works.py           # write
    python3 scripts/build-how-it-works.py --check   # fail if stale (CI)

The visual language is unchanged on purpose: Kalam hand-lettering, the same
four colour classes, the same arrowhead. Only the content moved.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))

BEGIN_H = '<!-- BEGIN how-it-works wide (generated by scripts/build-how-it-works.py) -->'
END_H = '<!-- END how-it-works wide -->'
BEGIN_V = '<!-- BEGIN how-it-works tall (generated by scripts/build-how-it-works.py) -->'
END_V = '<!-- END how-it-works tall -->'


# ── the figures, read from the data ────────────────────────────────────────

def figures():
    """Every number the drawing states, derived from the repo."""
    f = {}

    app = (ROOT / 'app.js').read_text(encoding='utf-8')
    i = app.index('const CITIES = {')
    depth, j = 0, app.index('{', i)
    for k in range(j, len(app)):
        if app[k] == '{':
            depth += 1
        elif app[k] == '}':
            depth -= 1
            if depth == 0:
                break
    f['live_cities'] = len(re.findall(r'(?m)^\s{4,8}[a-zA-Z0-9_-]+:\s*\{\s*name:', app[j:k + 1]))

    levels = json.loads((ROOT / 'data/tiles/_levels.json').read_text())
    feats = {a: b['features'] for a, b in levels.items()
             if isinstance(b, dict) and 'features' in b}
    f['wards'] = feats['ward']
    f['panchayats'] = feats['panchayat']
    f['villages'] = feats['village']

    bul = json.loads((ROOT / 'data/aqi-bulletins.json').read_text())['_meta']
    f['bulletin_cities'] = bul['cities']
    f['bulletin_window'] = bul['window'].replace('-', '–')

    dw = json.loads((ROOT / 'data/deweathered-national.json').read_text())['_meta']
    f['dw_cities'] = dw['cities']
    f['dw_window'] = dw['window'].replace('-', '\u2013')

    return f


def n(v):
    return f'{v:,}'


# ── the content ────────────────────────────────────────────────────────────
# Each source block: (colour class, heading, [lines]).
# Each output block: (heading, [sublines]).

def content(f):
    reads = [
        ('blu', 'Live feeds · every hour', [
            'CPCB CAAQMS',
            'WAQI',
            'OpenAQ + community sensors',
            'NASA FIRMS (farm fires)',
            'Open-Meteo (weather)',
        ]),
        ('amb', 'The measured record · years', [
            "CPCB's daily AQI bulletins",
            'XKDR station database (CPCB + US)',
            'NOAA weather history',
            '… what the models get checked against',
        ]),
        ('grn', 'Satellite + boundaries', [
            'SatPM2.5 · yearly + monthly',
            'Landsat 8/9 · surface heat',
            'ESA WorldCover · land cover',
            'LGD + Swachh Bharat Mission',
            '… every place, not every hour',
        ]),
    ]
    gets = [
        (f'Live AQI — {f["live_cities"]} cities', ['from the monitor network']),
        ('The map — every place in India',
         [f'{n(f["wards"])} wards · {n(f["panchayats"])} panchayats',
          f'{n(f["villages"])} villages · blocks · districts']),
        (f"CPCB's own bulletin, {f['bulletin_window']}",
         [f'{f["bulletin_cities"]} cities · days in each category',
          'with the monitor count beside each figure']),
        ('Weather removed from the trend',
         [f'{f["dw_cities"]} cities, {f["dw_window"]} · wind or policy?']),
        ('Ask JanVayu (AI)', ['answers, with its sources']),
        ('Forecast + farm fires', ['what is coming, and from where']),
        ('RTI + rights · alerts + open API', ['tools to act on it']),
    ]
    return reads, gets


def aria(f, reads, gets):
    src = '; '.join('%s — %s' % (h, ', '.join(x for x in ls if not x.startswith('…')))
                    for _, h, ls in reads)
    out = '; '.join('%s (%s)' % (h, ', '.join(ls)) for h, ls in gets)
    return ('How JanVayu works: three kinds of source feed one engine. %s. '
            'The engine verifies, computes and contextualizes them to produce: %s. '
            'Every figure is sourced and open.' % (src, out))


# ── drawing ────────────────────────────────────────────────────────────────

STYLE = """
    .k{font-family:'Kalam','Comic Sans MS',cursive}
    .h{font-family:'Kalam','Comic Sans MS',cursive;font-weight:700}
    .blu{fill:#e0f2fe;stroke:#075985;stroke-width:2.2}
    .amb{fill:#fdf0d5;stroke:#8a5300;stroke-width:2.2}
    .grn{fill:#dcfce7;stroke:#146c33;stroke-width:2.2}
    .tel{fill:#c3fae8;stroke:#0b7285;stroke-width:2.2}
    .ln{fill:none;stroke:#2f9e44;stroke-width:2.6}
  """
HEAD_INK = {'blu': '#075985', 'amb': '#8a5300', 'grn': '#146c33'}
MUTE = '#5b6b60'
DEFS = ('<defs><marker id="a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" '
        'markerHeight="6" orient="auto-start-reverse">'
        '<path d="M 0 0 L 10 5 L 0 10 z" fill="#2f9e44"/></marker></defs>')


def esc(s):
    return (s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
             .replace('·', '&#183;').replace('—', '&#8212;')
             .replace('–', '&#8211;').replace('…', '&#8230;'))


def txt(x, y, s, cls='k', size=13, fill=MUTE, anchor=None):
    a = f' text-anchor="{anchor}"' if anchor else ''
    return f'<text x="{x}" y="{y}" class="{cls}" font-size="{size}" fill="{fill}"{a}>{esc(s)}</text>'


def src_block(cls, x, y, w, head, lines, head_size=15, lh=20):
    """A source card: heading then one line per source. Height is derived."""
    h = 24 + 10 + lh * len(lines) + 6
    out = [f'<rect class="{cls}" x="{x}" y="{y}" width="{w}" height="{h}" rx="11"/>',
           txt(x + 16, y + 24, head, 'h', head_size, HEAD_INK[cls])]
    for i, ln in enumerate(lines):
        out.append(txt(x + 16, y + 46 + i * lh, ln, 'k', 13))
    return h, ''.join(out)


def out_block(x, y, w, head, subs):
    h = 32 + 17 * len(subs)
    out = [f'<rect class="tel" x="{x}" y="{y}" width="{w}" height="{h}" rx="11"/>',
           txt(x + 16, y + 24, head, 'h', 15, '#0b7285')]
    for i, s in enumerate(subs):
        out.append(txt(x + 16, y + 41 + i * 17, s, 'k', 12.5))
    return h, ''.join(out)


FOOT = 'every figure sourced + open  ·  no ads  ·  free forever'


def wide(f, titled=True):
    reads, gets = content(f)
    W, GAP = 920, 14
    LX, LW = 24, 252
    EX, EW = 330, 180
    RX, RW = 560, 336
    parts, top = [], 104

    y = top
    left_mid = []
    for cls, head, lines in reads:
        h, svg = src_block(cls, LX, y, LW, head, lines)
        parts.append(svg)
        left_mid.append(y + h / 2)
        y += h + GAP
    left_bottom = y - GAP

    y = top
    right_mid = []
    for head, subs in gets:
        h, svg = out_block(RX, y, RW, head, subs)
        parts.append(svg)
        right_mid.append(y + h / 2)
        y += h + 10
    right_bottom = y - 10

    ey = (top + max(left_bottom, right_bottom)) / 2 - 75
    parts.append(f'<rect class="grn" x="{EX}" y="{ey:.0f}" width="{EW}" height="150" rx="11"/>')
    cx = EX + EW / 2
    parts.append(txt(cx, ey + 28, 'JANVAYU ENGINE', 'h', 13, '#1e7a34', 'middle'))
    for i, w in enumerate(['Verify', 'Compute', 'Contextualize']):
        parts.append(txt(cx, ey + 60 + i * 32, w, 'h', 17, '#1e2a22', 'middle'))

    # sources into the engine, engine out to the results
    ec = ey + 75
    for i, m in enumerate(left_mid):
        yy = ec + (i - 1) * 14
        parts.append(f'<path class="ln" d="M{LX + LW} {m:.0f} L {(LX + LW + EX) / 2:.0f} {m:.0f} '
                     f'L {(LX + LW + EX) / 2:.0f} {yy:.0f} L {EX} {yy:.0f}" marker-end="url(#a)"/>')
    parts.append(f'<path class="ln" d="M{EX + EW} {ec:.0f} L {RX} {ec:.0f}" marker-end="url(#a)"/>')

    H = int(max(left_bottom, right_bottom)) + 90
    # On the homepage the section above the drawing already reads "How it
    # works / Where every number comes from", so a title inside it says the
    # same thing twice. The deck slide has no heading above it and keeps one.
    head = ([txt(W / 2, 34, 'How JanVayu works', 'h', 27, '#146c33', 'middle'),
             txt(W / 2, 58, 'independent sources, verified, made useful', 'k', 15, MUTE, 'middle')]
            if titled else [])
    head += [txt(LX + 4, 92, 'WHAT WE READ', 'h', 13, MUTE),
            txt(EX + 4, 92, 'WHAT WE DO', 'h', 13, MUTE),
            txt(RX + 4, 92, 'WHAT YOU GET', 'h', 13, MUTE)]
    foot = txt(W / 2, H - 28, FOOT, 'k', 14, MUTE, 'middle')
    return (f'<svg role="img" aria-label="{esc(aria(f, reads, gets))}" viewBox="0 0 {W} {H}" '
            f'xmlns="http://www.w3.org/2000/svg"><style>{STYLE}</style>'
            + ''.join(head) + ''.join(parts) + foot + DEFS + '</svg>')


def tall(f, titled=True):
    reads, gets = content(f)
    W, X, BW = 400, 22, 356
    parts, y = [], 98

    parts.append(txt(X + 4, 88, 'WHAT WE READ', 'h', 12, MUTE))
    for cls, head, lines in reads:
        h, svg = src_block(cls, X, y, BW, head, lines, lh=19)
        parts.append(svg)
        y += h + 12
    y += 8
    parts.append(f'<path class="ln" d="M200 {y - 16} L 200 {y + 10}" marker-end="url(#a)"/>')
    y += 22

    parts.append(f'<rect class="grn" x="{X}" y="{y}" width="{BW}" height="132" rx="11"/>')
    parts.append(txt(200, y + 26, 'JANVAYU ENGINE', 'h', 13, '#1e7a34', 'middle'))
    for i, w in enumerate(['Verify', 'Compute', 'Contextualize']):
        parts.append(txt(200, y + 56 + i * 28, w, 'h', 17, '#1e2a22', 'middle'))
    y += 132
    parts.append(f'<path class="ln" d="M200 {y + 6} L 200 {y + 32}" marker-end="url(#a)"/>')
    y += 44

    parts.append(txt(X + 4, y - 6, 'WHAT YOU GET', 'h', 12, MUTE))
    y += 12
    for head, subs in gets:
        h, svg = out_block(X, y, BW, head, subs)
        parts.append(svg)
        y += h + 10

    H = y + 46
    head = ([txt(200, 32, 'How JanVayu works', 'h', 24, '#146c33', 'middle'),
             txt(200, 54, 'independent sources, verified, made useful', 'k', 13, MUTE, 'middle')]
            if titled else [])
    foot = txt(200, H - 18, FOOT, 'k', 13, MUTE, 'middle')
    return (f'<svg role="img" aria-label="{esc(aria(f, reads, gets))}" viewBox="0 0 {W} {H}" '
            f'xmlns="http://www.w3.org/2000/svg"><style>{STYLE}</style>'
            + ''.join(head) + ''.join(parts) + foot + DEFS + '</svg>')


# ── writing it into the pages ──────────────────────────────────────────────

TARGETS = [
    ('index.html', 'both'),
    ('walkthrough/deck.html', 'wide'),
]


def splice(text, begin, end, body, path):
    if begin in text:
        a = text.index(begin) + len(begin)
        b = text.index(end)
        return text[:a] + '\n' + body + '\n' + text[b:]
    raise SystemExit(
        f'{path}: no {begin!r} marker. Wrap the existing <svg> in the BEGIN/END '
        f'comments once, by hand, so this script knows where it goes.')


def main():
    check = '--check' in sys.argv
    f = figures()
    w_plain, t_plain = wide(f, titled=False), tall(f, titled=False)
    w_titled = wide(f, titled=True)
    stale = []
    for rel, which in TARGETS:
        p = ROOT / rel
        s0 = p.read_text(encoding='utf-8')
        s = splice(s0, BEGIN_H, END_H, w_plain if which == 'both' else w_titled, rel)
        if which == 'both':
            s = splice(s, BEGIN_V, END_V, t_plain, rel)
        if s != s0:
            stale.append(rel)
            if not check:
                p.write_text(s, encoding='utf-8')
    if check:
        if stale:
            print('FAIL — the diagram is stale in: ' + ', '.join(stale))
            print('Run: python3 scripts/build-how-it-works.py')
            return 1
        print('PASS — the how-it-works diagram matches the data')
        return 0
    print(('rewrote ' + ', '.join(stale)) if stale else 'no change')
    for k, v in sorted(f.items()):
        print(f'  {k:18} {v}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
