#!/usr/bin/env bash
# Every command ci.yml actually runs, extracted from the workflow rather than
# kept as a second list that can drift from it. Regenerate with
# scripts/list-ci-checks.py whenever ci.yml changes.
set -u
echo "--- [guard-site-figures] python3 scripts/check-site-figures.py"; python3 scripts/check-site-figures.py >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/check-site-figures.py"; python3 scripts/check-site-figures.py 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/build-station-observed.py --check"; python3 scripts/build-station-observed.py --check >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/build-station-observed.py --check"; python3 scripts/build-station-observed.py --check 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/build-deweathered-national.py --check"; python3 scripts/build-deweathered-national.py --check >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/build-deweathered-national.py --check"; python3 scripts/build-deweathered-national.py --check 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/build-how-it-works.py --check"; python3 scripts/build-how-it-works.py --check >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/build-how-it-works.py --check"; python3 scripts/build-how-it-works.py --check 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/check-asset-urls.py"; python3 scripts/check-asset-urls.py >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/check-asset-urls.py"; python3 scripts/check-asset-urls.py 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/check-nav-coverage.py"; python3 scripts/check-nav-coverage.py >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/check-nav-coverage.py"; python3 scripts/check-nav-coverage.py 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/check-critical-css.py"; python3 scripts/check-critical-css.py >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/check-critical-css.py"; python3 scripts/check-critical-css.py 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/check-asset-stamps.py"; python3 scripts/check-asset-stamps.py >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/check-asset-stamps.py"; python3 scripts/check-asset-stamps.py 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/check-theme-contrast.py"; python3 scripts/check-theme-contrast.py >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/check-theme-contrast.py"; python3 scripts/check-theme-contrast.py 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/check-uppercase-units.py"; python3 scripts/check-uppercase-units.py >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/check-uppercase-units.py"; python3 scripts/check-uppercase-units.py 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/build-aqi-bulletins.py --check"; python3 scripts/build-aqi-bulletins.py --check >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/build-aqi-bulletins.py --check"; python3 scripts/build-aqi-bulletins.py --check 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/check-bulletin-parser.py"; python3 scripts/check-bulletin-parser.py >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/check-bulletin-parser.py"; python3 scripts/check-bulletin-parser.py 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/check-about-currency.py"; python3 scripts/check-about-currency.py >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/check-about-currency.py"; python3 scripts/check-about-currency.py 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/check-workshop-decks.py"; python3 scripts/check-workshop-decks.py >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/check-workshop-decks.py"; python3 scripts/check-workshop-decks.py 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/build-blog-index.py --check"; python3 scripts/build-blog-index.py --check >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/build-blog-index.py --check"; python3 scripts/build-blog-index.py --check 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/build-gallery-manifest.py --check"; python3 scripts/build-gallery-manifest.py --check >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/build-gallery-manifest.py --check"; python3 scripts/build-gallery-manifest.py --check 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/build-district-history.py --check"; python3 scripts/build-district-history.py --check >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/build-district-history.py --check"; python3 scripts/build-district-history.py --check 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/check-hero-currency.py"; python3 scripts/check-hero-currency.py >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/check-hero-currency.py"; python3 scripts/check-hero-currency.py 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/check-retracted-claims.py"; python3 scripts/check-retracted-claims.py >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/check-retracted-claims.py"; python3 scripts/check-retracted-claims.py 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/check-factcheck-freshness.py"; python3 scripts/check-factcheck-freshness.py >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/check-factcheck-freshness.py"; python3 scripts/check-factcheck-freshness.py 2>&1 | tail -6; }
echo "--- [guard-site-figures] python3 scripts/build-deweathered.py --check"; python3 scripts/build-deweathered.py --check >/dev/null 2>&1 || { echo "   FAIL: python3 scripts/build-deweathered.py --check"; python3 scripts/build-deweathered.py --check 2>&1 | tail -6; }
echo "=== done ==="
